### ISSUE TITLE
Hey, cool library! 

### ISSUE THREAD

**Issue by feross** [chadnickbok/librtcdcpp#17]
Great work. Once this is further along, I'd love to help write the node.js bindings for this. One question: Why did you fork this from https://github.com/xhs/librtcdc ?

**Comment by chadnickbok** [comment]
Two main reasons; I had a hard time getting librtcdc to work (I actually made a few patches before giving up), and I wanted to be able to use things like C++ threads to make cross-platform work a little more straightforward. This library was originally written targeting windows first.

**Comment by feross** [comment]
Thanks for explaining. Cheers!
