### ISSUE TITLE
Implementing Close DataChannel

### ISSUE THREAD

**Issue by PowerInside** [chadnickbok/librtcdcpp#20]
I've noticed that [Close() is a TODO](https://github.com/chadnickbok/librtcdcpp/blob/master/src/DataChannel.cpp#L62) at the moment. 
To [implement this](https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13#section-6.7), is it sufficient to use `usrsctp_deregister_address()` as it's done [here](https://github.com/xhs/librtcdc/blob/master/src/sctp.c#L178)?

**Comment by chadnickbok** [comment]
It _should_ be, but that would be well worth a double-check when implementing.

Thanks for the reminder, I'll try to take a look at implementing this, or you're more than welcome to submit a PR :)

**Comment by PowerInside** [comment]
Ah okay, I'm looking at it too. I'm trying to ensure that the testclient program could terminate safely so I could then check for any memory leaks with valgrind.

**Comment by chadnickbok** [comment]
Perfect - one challenge I've had with Valgrind is that it gets super upset with OpenSSL. You can create ignore lists for a lot of the OpenSSL warnings that should help sort the signal from the noise.

**Comment by PowerInside** [comment]
I think I got this working. Will send a PR soon once I do a bit of clean up :)

**Comment by PowerInside** [comment]
PR: https://github.com/chadnickbok/librtcdcpp/pull/24
